### ISSUE TITLE
Deleting branches

### ISSUE THREAD

**Issue by jema28** [fack2/University-Autocomplete#14]
You have a lot of open merged branches, please delete these! It's good to get into the habit of deleting them straight after you merge the PRs.

<img width="910" alt="Screenshot 2019-07-11 at 08 36 40" src="https://user-images.githubusercontent.com/25960351/61024673-0b927100-a3b7-11e9-912c-11345f381b21.png">

**Comment by sara219** [comment]
We deleted the branches
