### ISSUE TITLE
Input box size

### ISSUE THREAD

**Issue by jema28** [fack2/University-Autocomplete#15]
Firstly, I love the design, awesome job! One thing I'd say is it would be a better user experience if the input box didn't change size and started off as big as the dropdowns. 

<img width="187" alt="Screenshot 2019-07-11 at 08 40 38" src="https://user-images.githubusercontent.com/25960351/61024869-9d9a7980-a3b7-11e9-8cea-dba2236e78ab.png">

**Comment by saharAdem** [comment]
fixed
@jema28
