### ISSUE TITLE
Spelling errors

### ISSUE THREAD

**Issue by jema28** [fack2/University-Autocomplete#25]
Please be careful of spelling errors e.g. `Content-Type` and `application`:

https://github.com/fack2/University-Autocomplete/blob/6586299d3cc6854379fdc9bf1a661a146989d3b2/src/handler.js#L19

https://github.com/fack2/University-Autocomplete/blob/6586299d3cc6854379fdc9bf1a661a146989d3b2/src/handler.js#L47

https://github.com/fack2/University-Autocomplete/blob/6586299d3cc6854379fdc9bf1a661a146989d3b2/src/handler.js#L66

**Comment by sara219** [comment]
DONE :)
