### ISSUE TITLE
Console logs

### ISSUE THREAD

**Issue by jema28** [fack2/University-Autocomplete#28]
Logging is great for development but usually you should avoid pushing up logs to the master. Please delete go through all files and delete the console logs. Here are some examples but there are lot more.

https://github.com/fack2/University-Autocomplete/blob/6586299d3cc6854379fdc9bf1a661a146989d3b2/public/js/script.js#L3
https://github.com/fack2/University-Autocomplete/blob/6586299d3cc6854379fdc9bf1a661a146989d3b2/public/js/script.js#L13

**Comment by sara219** [comment]
we deleted it
